// RobotBuilder Version: 4.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Command.

package frc.robot.auto.commands;
import edu.wpi.first.wpilibj.Timer;
import edu.wpi.first.wpilibj2.command.CommandBase;


public class delayCmd extends CommandBase {
    private double m_timeOut;
    Timer delayTimer = new Timer();

    public delayCmd(double timeOut) {
        m_timeOut = timeOut;
    }

    @Override
    public void initialize() {
        delayTimer.reset();
        delayTimer.start();
        System.out.println("---------- delayCmd Has Started");
    }

    @Override
    public void execute() {
    }

    @Override
    public void end(boolean interrupted) {
    }

     @Override
    public boolean isFinished() {
        if (delayTimer.get() > m_timeOut) { System.out.println("---------- delayCmd Has Ended"); return true; }
        return false;
    }

    @Override
    public boolean runsWhenDisabled() {
        return false;
    }
}
